name: cinema_plus
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  dio: ^5.5.0+1
  get_it: ^7.7.0
  injectable: ^2.4.4
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  shared_preferences: ^2.3.1
  cloud_firestore: ^4.14.0
  gap: ^3.0.1
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  jiffy: ^6.3.1
  dartz: ^0.10.1
  formz: ^0.7.0
  form_inputs:
    path: packages/form_inputs
  cache:
    path: packages/cache
  google_sign_in: ^6.2.1
  firebase_crashlytics: ^3.5.7
  logger: ^2.4.0
  salomon_bottom_bar: ^3.3.2
  ionicons: ^0.2.2
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.0
  go_router: ^14.2.3
  pretty_qr_code: ^3.3.0
  toastification: ^2.2.0
  adaptive_theme: ^3.6.0
  infinite_scroll_pagination: ^4.0.0
  animations: ^2.0.11
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  injectable_generator: ^2.6.2
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  freezed: ^2.5.2


flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true

        
    
    
                                      