// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCze-BFzUw56GuOuK7g1jkB3xC4w5zlQD8',
    appId: '1:469101213143:web:6934103f2d0d243ac70792',
    messagingSenderId: '469101213143',
    projectId: 'cinemaplus-ac4a8',
    authDomain: 'cinemaplus-ac4a8.firebaseapp.com',
    storageBucket: 'cinemaplus-ac4a8.appspot.com',
    measurementId: 'G-HCHN4WTMTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3u7awRwpXI6DBUy_WreOLu8bOWOsfNUQ',
    appId: '1:469101213143:android:b76611a92134c266c70792',
    messagingSenderId: '469101213143',
    projectId: 'cinemaplus-ac4a8',
    storageBucket: 'cinemaplus-ac4a8.appspot.com',
  );
}
